### PR TITLE
Enhancement: jump to tab by URL/title/index

### PR DESCRIPTION
**Pull request by pikou1995**
I hope it can be helpful: )

### CODE REVIEW

**Comment by mikecrittenden** [comment]
This looks fantastic. Thank you so much!

**Comment by p3lim** [comment]
Please release this :)

**Comment by gfsd3v** [comment]
Hey, sorry to bother you guys, but I didnt find anywhere how to use the index feature, I want to change from "alt" to "ctrl" I tried these:

image
image

**Comment by SamuelWN** [comment]
@gfsd3v 
I was similarly confused, but figured it out. Your approach in the first image is basically correct, but you then need to select the ">" to the left of the shortcut field and then provide it the index you want it to switch to. 
(It's been a long time since I last used it and had kinda forgotten that that the drop-down existed.)
For `alt+0` you can simply set "Behavior" to "Last tab".

**Pull request merged**
