### PR TITLE
add 'move tab to new window' action

### PR DESCRIPTION
**Pull request by jpalmieri**
Addresses https://github.com/mikecrittenden/shortkeys/issues/158

### CODE REVIEW

**Comment by jpalmieri** [comment]
@mikecrittenden can you take a look?

**Comment by mikecrittenden** [comment]
Heya @jpalmieri I'm sorry I'm SUPER behind on PRs and issues here. Trying to keep my head above water on a client project at the moment and I promise to come back around to this when we launch (getting close).

**Comment by mikecrittenden** [comment]
Actually this PR looks dead simple and totally fine so I went ahead and merged, but it'll be a bit before I can build a new release.

**Comment by mikecrittenden** [comment]
Thank you!

**Comment by jpalmieri** [comment]
All good; thanks for taking g a look. I hope you get some time to relax
soon!

**Pull request merged**
