### PR TITLE
Add 'Show latest download' option

### PR DESCRIPTION
**Pull request by Sergej-Popov**
Hey @mikecrittenden, please consider merging this.
It requires new permission 'downloads', but I think it is worth it, as it is super useful.

### CODE REVIEW

**Comment by mikecrittenden** [comment]
This is a fantastic idea and a simple implementation. I *just* pushed a release which added a new permission, which means everyone *just* had to manually re-enable shortkeys, so I'm going to hold off on merging this for now to let everyone have a couple weeks without having to re-enable it again, but I'll be back.

**Comment by Sergej-Popov** [comment]
Sure, makes sense. I'm currently running this branch locally as I use this a lot.

**Comment by Sergej-Popov** [comment]
@mikecrittenden bump 🙂

**Comment by mikecrittenden** [comment]
Thanks again! It'll be in the next release!

**Pull request merged**
