### PR TITLE
Fallback to browser.storage.local instead of localstorage for firefox…

### PR DESCRIPTION
**Pull request by pmalecka**
…, fixes mikecrittenden/shortkeys#113

added debug options for firefox using web-ext

### CODE REVIEW

**Comment by mikecrittenden** [comment]
@pmalecka you rock, thanks for this. Looks like the build failed because of code style stuff:

```
standard: Run `standard --fix` to automatically fix some problems.

  /home/travis/build/mikecrittenden/shortkeys/app/scripts/background.js:283:5: Expected space(s) after "if".

  /home/travis/build/mikecrittenden/shortkeys/app/scripts/background.js:284:20: 'browser' is not defined.

  /home/travis/build/mikecrittenden/shortkeys/app/scripts/background.js:285:20: The array literal notation [] is preferrable.

  /home/travis/build/mikecrittenden/shortkeys/app/scripts/background.js:295:7: Expected space(s) after "else".

  /home/travis/build/mikecrittenden/shortkeys/app/scripts/options.js:246:5: Expected space(s) after "if".

  /home/travis/build/mikecrittenden/shortkeys/app/scripts/options.js:247:7: 'browser' is not defined.

  /home/travis/build/mikecrittenden/shortkeys/app/scripts/options.js:247:42: Extra semicolon.

  /home/travis/build/mikecrittenden/shortkeys/app/scripts/options.js:248:7: Expected space(s) after "else".

  /home/travis/build/mikecrittenden/shortkeys/app/scripts/options.js:266:12: Expected space(s) after "if".

  /home/travis/build/mikecrittenden/shortkeys/app/scripts/options.js:267:7: 'browser' is not defined.
```

Also, is this backwards compatible? Like, will this just work with all of the FF users who already have settings saved to localStorage? If so, it seems like we should probably just make Chrome use this method as well since it seems like the best practice, and would get rid of a lot of FF-specific checks. Thoughts? I'd be happy to test as well, but I can't until tomorrow.

**Comment by pmalecka** [comment]
Oh, thanks. I do not have a travis build set up. I'll fix those.

The backwards compatibility is a bit funny. In 2.2.6 - I actually broke that in the release by not merging my changes to storage I made for 2.2.0.
See the last paragraph here: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage It basically says that when using localstorage in extensions - Firefox will clear this data when clearing browsing data, or does not even save it between sessions if history is disabled (what happend here).

So in 2.2.7 we are actually backwards compabile with 2.20 and 2.2.19 which I released to AMO.

If we're fairly sure that noone is using v1 on chrome, then I see no problem there. Just change the `browser.storage` to `chrome.storage` and remove promises (since FF API uses promises instead of callbacks) and it shold work just fine.

**Comment by mikecrittenden** [comment]
@pmalecka the build results are above in this PR if that's what you mean?

Awesome, I will fill with this tomorrow then.

**Comment by pmalecka** [comment]
@mikecrittenden yeah, I see that now, thanks. Is there any way to run this locally before submitting a PR?

**Comment by mikecrittenden** [comment]
Yeah just run `npm run lint` from the root.

**Comment by pmalecka** [comment]
Ok, so I fixed those linting errors now, and tried merging the code so it would work for chrome as well. 

Not sure about the code on L295 in background.js. I can confirm that the sendresponse function absolutely has to be called before the chrome.runtime.onMessage.addListener callback function returns. That's why I added the promise there (that is what has worked for me on the Firefox side, but it's been a while since I wrote that code). Maybe an another approach would be cleaner, but I cannot really think of anything else at this stage.

**Comment by mikecrittenden** [comment]
@pmalecka I *think* this commit successfully removes the need for the Promise. It works consistently on my end at least. https://github.com/mikecrittenden/shortkeys/commit/914786af4a3a877994beab2a7ed6c5a7f1d8a9a2

I think more testing is needed here. It seemed like I had to manually go into the settings and re-save them for it to get picked up which would be a problem if that's true. Overall though, I think this is looking pretty good. Any thoughts?

**Comment by pmalecka** [comment]
That is a much cleaner approach, I like it.

Yeah, the behavior you described is caused by how those settings are saved in options.js. They were saved to storage.sync and also to localStorage, but not to storage.local. From there on, those settings were retrieved from localStorage, not storage.sync (by the background and content scripts). That is probably why you are seeing that kind of behavior.

Maybe it would actually make sense to only store to storage.sync and retrieve from storage.sync. I see 2 items that we need to think about there:
1. What happens if chrome/FF does not have sync enabled (user is not logged in or does not have sync enabled for extensions). FF seems to handle this by just storing this data locally, so when storage.sync.get is called, it just returns the data (but nothing is synced).
2. In the FF extension - we always relied on storage.local instead of localstorage. I only added storage.sync in version 2.2.6 (first version build from our merged codebase). So before making the change above, I need to make sure majority of our users are on 2.2.6 or higher, before introducing the change to storage.sync.

What do you think?

**Comment by mikecrittenden** [comment]
Hey @pmalecka I haven't forgotten about this! I've just been out of commission with the holidays. I'll circle back to this ASAP.

**Comment by pmalecka** [comment]
Same here :) Enjoy the holidays!

**Comment by mikecrittenden** [comment]
Closing some old PRs because most everything is updated now.

**Pull request closed without merging**
